### PR TITLE
wait for create iam role

### PR DESCRIPTION
**Pull request by pei0804**

### CODE REVIEW

**Comment by pei0804** [comment]
not yet fix.

```
Error: Error creating Step Function State Machine: AccessDeniedException: 'arn:aws:iam::xxx:role/EcsTaskScheduledExecutionStepFunction' is not authorized to create managed-rule.
        status code: 400, request id: b97e7703-effb-4f14-bb58-7304aff371f8

  on ../../main.tf line 37, in resource "aws_sfn_state_machine" "this":
  37: resource aws_sfn_state_machine this {


make: *** [apply] Error 1
```

After a moment I one more apply so success.
hmm.

**Comment by pei0804** [comment]
cloudtrail log

```

{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "AIDAJEYC756DDRURBBCPC",
        "arn": "arn:aws:iam::xxx:user/pei0804",
        "accountId": "xxx",
        "accessKeyId": "xxx",
        "userName": "pei0804"
    },
    "eventTime": "2020-04-12T08:39:08Z",
    "eventSource": "states.amazonaws.com",
    "eventName": "CreateStateMachine",
    "awsRegion": "ap-northeast-1",
    "sourceIPAddress": "hoge",
    "userAgent": "aws-sdk-go/1.29.20 (go1.13.7; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.19 (+https://www.terraform.io)",
    "errorCode": "AccessDenied",
    "errorMessage": "An unknown error occurred",
    "requestParameters": {
        "name": "EcsTaskScheduledExecution",
        "tags": [],
        "roleArn": "arn:aws:iam::851669633371:role/EcsTaskScheduledExecutionStepFunction",
        "definition": "HIDDEN_DUE_TO_SECURITY_REASONS"
    },
    "responseElements": null,
    "requestID": "b97e7703-effb-4f14-bb58-7304aff371f8",
    "eventID": "b2800420-d40d-4aab-b4d7-fe8c50c26d02",
    "eventType": "AwsApiCall",
    "recipientAccountId": "xxx"
}
```

**Comment by pei0804** [comment]
I understand.
This error reason is IAM Role or IAM Role policy creating not complete.
In my assumption, role management and state machine management are separate, so I will not fix this.

**Comment by benmanns** [comment]
You might have luck using [`depends_on`](https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies) to wait for the IAM role and policy attachments to be created.

**Pull request closed without merging**
